# Generated by Django 6.0.4 on 2026-06-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('top_up', 'Пополнение баланса'), ('lesson_payment', 'Оплата урока'), ('hold', 'Резервирование средств'), ('release', 'Зачисление репетитору'), ('payout', 'Выплата репетитору'), ('refund', 'Возврат ученику'), ('commission', 'Комиссия платформы'), ('listing_fee', 'Размещение анкеты'), ('pro_subscription', 'Подписка Znanium Pro')], max_length=20),
        ),
    ]
