# Generated by Django 6.0.4 on 2026-06-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_data_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_data_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
