# Generated by Django 6.0.4 on 2026-06-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_personal_data_consent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='class_level',
            field=models.CharField(blank=True, help_text='Например: 9 класс, студент, взрослый', max_length=40),
        ),
    ]
