# Generated by Django 4.2.29 on 2026-04-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lesson_format', models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Очный'), ('both', 'Очно и онлайн')], default='online', max_length=20)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('metro', models.CharField(blank=True, max_length=120)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('verification_status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='pending', max_length=20)),
                ('diploma', models.FileField(blank=True, null=True, upload_to='tutors/diplomas/')),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='tutors/videos/')),
                ('identity_verified', models.BooleanField(default=False)),
                ('subjects', models.ManyToManyField(blank=True, related_name='tutors', to='tutors.subject')),
            ],
            options={
                'ordering': ['-rating', 'price_per_hour'],
            },
        ),
    ]
