# Generated by Django 4.2.29 on 2026-04-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_profileview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='metro',
        ),
    ]
