# Generated by Django 4.2.29 on 2026-04-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_remove_tutorprofile_metro'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='photo',
            field=models.URLField(blank=True, help_text='URL фотографии репетитора', max_length=500),
        ),
    ]
