# Generated by Django 4.2.29 on 2026-04-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0005_tutorprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(blank=True, default='#7c3aed', help_text='Цвет в формате HEX', max_length=7),
        ),
        migrations.AddField(
            model_name='subject',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome иконка (например: fa-calculator)', max_length=50),
        ),
    ]
