# Generated by Django 6.0.4 on 2026-06-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0006_subject_color_subject_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='photo_file',
            field=models.FileField(blank=True, null=True, upload_to='tutors/photos/'),
        ),
    ]
