# Generated by Django 6.0.4 on 2026-06-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0007_tutorprofile_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome иконка, например fa-calculator', max_length=50),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='pending', max_length=20),
        ),
    ]
