# Generated by Django 6.0.4 on 2026-06-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lessonmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsession',
            name='meeting_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='lessonorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждён'), ('completed', 'Проведён'), ('cancelled', 'Отменён'), ('in_dispute', 'В споре')], default='pending', max_length=20),
        ),
    ]
